service: backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x

functions:
  get_todo_list:
    handler: src/functions/get_todo_list.handler
    events:
      - httpApi:
          path: /todo
          method: get
  add_todo:
    handler: src/functions/add_todo.handler
    events:
      - httpApi:
          path: /todo
          method: post

plugins:
  - serverless-esbuild
  - serverless-offline
